from art.attacks.evasion.projected_gradient_descent.projected_gradient_descent import ProjectedGradientDescent
from art.attacks.evasion.projected_gradient_descent.projected_gradient_descent_numpy import \
    ProjectedGradientDescentNumpy
from art.attacks.evasion.projected_gradient_descent.projected_gradient_descent_pytorch import \
    ProjectedGradientDescentPytorch
from art.attacks.evasion.projected_gradient_descent.projected_gradient_descent_tensorflow_v2 import \
    ProjectedGradientDescentTensorflowV2
