# Container image
#FROM pytorchlightning/pytorch_lightning:base-xla-py3.6-torch1.6
#FROM python:3.8.3-alpine
FROM ubuntu

# Copy code file to the container
#COPY deepspeech_docker_setup.sh /deepspeech_docker_setup.sh

# Code file to execute when the docker container starts
#ENTRYPOINT ["/deepspeech_docker_setup.sh"]

#RUN apk add --no-cache python3-dev libffi-dev gcc git && pip3 install --upgrade pip
#RUN apk add musl-dev openssl-dev cargo
#ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y install sudo
#RUN sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update && sudo apt install python3.6
#RUN sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install python3-dev libffi-dev gcc git musl-dev
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install python3-dev gcc git python3-pip
RUN pip3 install --upgrade pip
RUN pip install setuptools
RUN pip install wheel
RUN pip install torch==1.6.0

RUN pip install fairscale

RUN git clone https://github.com/SeanNaren/deepspeech.pytorch.git
RUN cd deepspeech.pytorch && pip install -r requirements.txt
RUN pip install -e . # Dev install
RUN cd ..

RUN git clone https://github.com/Trusted-AI/adversarial-robustness-toolbox.git
RUN cd adversarial-robustness-toolbox
RUN pip install .
RUN cd ..