# Container image
FROM pytorchlightning/pytorch_lightning:base-xla-py3.6-torch1.6

# Copy code file to the container
COPY deepspeech_docker_setup.sh /deepspeech_docker_setup.sh

# Code file to execute when the docker container starts
ENTRYPOINT ["/deepspeech_docker_setup.sh"]
