name: CI PyTorchDeepSpeech v3
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
  pull_request:
    paths-ignore:
      - '*.md'

  # Run on merge queue
  merge_group:

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

  # Run scheduled CI flow daily
  schedule:
    - cron: '0 8 * * 0'

jobs:
  test_deepspeech_v3_torch_2_1_1:
    name: PyTorchDeepSpeech v3 / PyTorch 2.1.1
    runs-on: ubuntu-latest
    container: bbuesser/art_testing_env_deepspeech_v3_torch_2_1_1:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache CIFAR-10 dataset
        uses: actions/cache@v4
        with:
          path: ~/.art/data/cifar-10-batches-py
          key: cifar10-dataset-cache-v1

      - name: Cache MNIST dataset
        uses: actions/cache@v4
        with:
          path: ~/.art/data/mnist.npz
          key: mnist-dataset-cache-v1

      - name: Download and extract CIFAR-10 if not cached
        run: |
          mkdir -p ~/.art/data
          if [ ! -d ~/.art/data/cifar-10-batches-py ]; then
            echo "Downloading CIFAR-10 dataset..."
            if curl -L -f -o cifar-10-python.tar.gz https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz; then
              echo "Downloaded from www.cs.toronto.edu"
            else
              echo "Primary download failed, trying Dropbox mirror..."
              curl -L -o cifar-10-python.tar.gz "https://www.dropbox.com/scl/fi/6mhiq4rtfszqrosasp8a9/cifar-10-batches-py.tar.gz?rlkey=g6v114un4je233j52tu5tdsbe&st=gxo2e50q&dl=1"
            fi
            tar -xzf cifar-10-python.tar.gz -C ~/.art/data/
          else
            echo "CIFAR-10 already cached."
          fi

      - name: Download MNIST if not cached
        run: |
          mkdir -p ~/.art/data
          if [ ! -f ~/.art/data/mnist.npz ]; then
            echo "Downloading MNIST dataset..."
            curl -L -o ~/.art/data/mnist.npz https://s3.amazonaws.com/img-datasets/mnist.npz
          else
            echo "MNIST already cached."
          fi

      - name: Run Test Action
        uses: ./.github/actions/deepspeech-v3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
