name: CI PyTorchDeepSpeech v3
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
  pull_request:
    paths-ignore:
      - '*.md'

  # Run on merge queue
  merge_group:

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

  # Run scheduled CI flow daily
  schedule:
    - cron: '0 8 * * 0'

jobs:
  test_deepspeech_v3_torch_2_1_1:
    name: PyTorchDeepSpeech v3 / PyTorch 2.1.1
    runs-on: ubuntu-latest
    container: bbuesser/art_testing_env_deepspeech_v3_torch_2_1_1:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Test Action
        uses: ./.github/actions/deepspeech-v3
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
