name: CI TensorFlow v1
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
  pull_request:
    paths-ignore:
      - '*.md'

  # Run on merge queue
  merge_group:

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

  # Run scheduled CI flow daily
  schedule:
    - cron: '0 8 * * 0'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: TensorFlow 1.15.5 (Keras 2.2.5 Python 3.7)
            framework: tensorflow
            python: 3.7
            tensorflow: 1.15.5
            tf_version: v1
            keras: 2.2.5

    name: ${{ matrix.name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y -q install ffmpeg libavcodec-extra
          python -m pip install --upgrade pip setuptools wheel
          pip install -q -r <(sed '/^pandas/d;/^scipy/d;/^matplotlib/d;/^xgboost/d;/^tensorflow/d;/^keras/d;/^jax/d;/^torch/d;/^Pillow/d;/^h5py/d;/^kornia/d;/^scikit-learn/d;/^pytest-mock/d;/^GPy/d;/^lief/d;/^statsmodels/d' requirements_test.txt)
          pip install pandas==1.3.5
          pip install scipy==1.7.2
          pip install matplotlib==3.5.3
          pip install xgboost==1.6.2
          pip install protobuf==3.20.1
          pip install tensorflow==${{ matrix.tensorflow }}
          pip install keras==${{ matrix.keras }}
          pip install numpy==1.20
          pip install torch==1.13.1
          pip install torchaudio==0.13.1
          pip install torchvision==0.14.1+cpu
          pip install Pillow==9.5.0
          pip install h5py==3.8.0
          pip install kornia==0.6.12
          pip install scikit-learn==1.0.2
          pip install pytest-mock~=3.11.1
          pip install GPy~=1.10.0
          pip install lief==0.12.3
          pip install statsmodels==0.13.5
          pip list
      - name: Run Tests
        run: ./run_tests.sh ${{ matrix.framework }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
